/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ProfileComponent {
        /**
          * The Account Number
         */
        "accountNumber": string;
    }
}
declare global {
    interface HTMLProfileComponentElement extends Components.ProfileComponent, HTMLStencilElement {
    }
    var HTMLProfileComponentElement: {
        prototype: HTMLProfileComponentElement;
        new (): HTMLProfileComponentElement;
    };
    interface HTMLElementTagNameMap {
        "profile-component": HTMLProfileComponentElement;
    }
}
declare namespace LocalJSX {
    interface ProfileComponent {
        /**
          * The Account Number
         */
        "accountNumber"?: string;
    }
    interface IntrinsicElements {
        "profile-component": ProfileComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "profile-component": LocalJSX.ProfileComponent & JSXBase.HTMLAttributes<HTMLProfileComponentElement>;
        }
    }
}
